kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploywebfairq
  namespace: project-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webFairQ
  template:
    metadata:
      labels:
        app: webFairQ
    spec:
      containers:
        - name: fairq-web
          image: 'golobart/django-fairqueue-compose:latest'
          ports:
            - containerPort: 8000
              protocol: TCP
          securityContext:
            runAsUser: 0
          env:
            - name: FAIRQ_ENV
              value: development
            - name: FAIRQ_COMPOSE
              value: 'yes'
            - name: FAIRQ_OPENSHIFT
              value: 'yes'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%


