kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mysql
  namespace: project-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
