pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'python --version'
                sh 'echo "Hello World"'
                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                '''
            }
        }
        stage('Deploy') {
            steps {
                retry(3) {
                    sh 'ls '
                }

                timeout(time: 3, unit: 'MINUTES') {
                    sh 'ls -ltr'
                }
            }
        }
    }
}
