# Generated by Django 3.0.5 on 2020-04-25 07:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, verbose_name='Calendar owner')),
                ('name', models.CharField(max_length=200, verbose_name='Calendar name')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Calendar description')),
                ('year', models.DecimalField(blank=True, decimal_places=0, max_digits=4, verbose_name='Calendar year')),
                ('ini_day', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='Calendar first day')),
                ('end_day', models.DateField(verbose_name='Calendar last day')),
                ('template', models.BooleanField(verbose_name='Is calendar template')),
                ('next', models.CharField(blank=True, max_length=32, verbose_name='Next calendar')),
                ('prev', models.CharField(blank=True, max_length=32, verbose_name='Previous calendar')),
                ('open', models.BooleanField(verbose_name='Is calendar open')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ini_hour', models.CharField(max_length=200)),
                ('end_hour', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('NO', 'Normal'), ('ID', 'Interday scheduling'), ('M2', 'More than 24 hours')], default='NO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Resource name')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Resource description')),
                ('text_title', models.CharField(blank=True, max_length=200, verbose_name='Resource title')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapp.Calendar')),
            ],
        ),
        migrations.CreateModel(
            name='DaySpecWT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_minutes', models.IntegerField(verbose_name='Duration in minutes of each booking slot')),
                ('type', models.CharField(choices=[('DA', 'Single day'), ('DR', 'Range of days'), ('WD', 'Day of week'), ('MD', 'Day of month'), ('MO', 'Full month')], default='DA', max_length=2)),
                ('day', models.DateField()),
                ('end_day', models.DateField()),
                ('week_day', models.DecimalField(decimal_places=0, max_digits=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('month_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('from_day', models.DateField()),
                ('to_day', models.DateField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Calendar')),
                ('working_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.WorkingTime')),
            ],
        ),
        migrations.CreateModel(
            name='DaysOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DA', 'Single day'), ('DR', 'Range of days'), ('WD', 'Day of week'), ('MD', 'Day of month'), ('MO', 'Full month')], default='DA', max_length=2)),
                ('day', models.DateField()),
                ('end_day', models.DateField()),
                ('week_day', models.DecimalField(decimal_places=0, max_digits=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('month_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('from_day', models.DateField()),
                ('to_day', models.DateField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Calendar')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarDefWT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_days', models.IntegerField(verbose_name='Number of days granted to be booked')),
                ('slot_minutes', models.IntegerField(verbose_name='Duration in minutes of each booking slot')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Calendar')),
                ('working_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.WorkingTime')),
            ],
        ),
    ]
