# Generated by Django 3.0.5 on 2020-04-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysoff',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Days off description'),
        ),
        migrations.AddField(
            model_name='daysoff',
            name='name',
            field=models.CharField(default='xxx', max_length=200, verbose_name='Days off name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workingtime',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Working time description'),
        ),
        migrations.AddField(
            model_name='workingtime',
            name='name',
            field=models.CharField(default='yyy', max_length=200, verbose_name='Working time name'),
            preserve_default=False,
        ),
    ]
