# Generated by Django 3.0.5 on 2020-04-27 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20200425_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='next',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='prev',
        ),
    ]
