# Generated by Django 3.0.5 on 2020-04-27 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20200427_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='next',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_cal', to='adminapp.Calendar'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='prev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_cal', to='adminapp.Calendar'),
        ),
    ]
