# Generated by Django 3.0.5 on 2020-05-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_auto_20200522_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Calendar description'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='year',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Calendar year'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Resource description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='text_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Resource title'),
        ),
    ]
