# Generated by Django 3.0.5 on 2020-05-25 08:46

import adminapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_auto_20200522_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Working time description'),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='end_hour',
            field=models.CharField(help_text='Please use the following format: <em>hh:mm</em>.', max_length=5, validators=[django.core.validators.MinLengthValidator(5, 'Too short'), adminapp.models.validate_hhmm_format]),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='ini_hour',
            field=models.CharField(help_text='Please use the following format: <em>hh:mm</em>.', max_length=5),
        ),
    ]
