# Generated by Django 3.0.5 on 2020-05-25 09:34

import adminapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_auto_20200525_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='end_hour',
            field=models.CharField(help_text='Please use the following format: <em>hh:mm</em>.', max_length=5, validators=[adminapp.models.validate_hhmm_format], verbose_name='Final hour'),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='ini_hour',
            field=models.CharField(help_text='Please use the following format: <em>hh:mm</em>.', max_length=5, validators=[adminapp.models.validate_hhmm_format], verbose_name='Initial hour'),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='type',
            field=models.CharField(choices=[('NO', 'Normal'), ('ID', 'Interday scheduling'), ('M2', 'More than 24 hours')], default='NO', max_length=2, verbose_name='Type of WT'),
        ),
    ]
