# Generated by Django 3.0.5 on 2020-05-25 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_auto_20200525_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daysoff',
            name='calendar',
        ),
        migrations.AlterField(
            model_name='daysoff',
            name='week_day',
            field=models.DecimalField(decimal_places=0, max_digits=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
