# Generated by Django 3.0.5 on 2020-05-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_auto_20200525_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysoff',
            name='month',
            field=models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('', 'August'), ('', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3),
        ),
        migrations.AlterField(
            model_name='daysoff',
            name='week_day',
            field=models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=2),
        ),
    ]
