# Generated by Django 3.0.5 on 2020-05-25 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_auto_20200525_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysoff',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daysoff',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Days off description'),
        ),
        migrations.AlterField(
            model_name='daysoff',
            name='end_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daysoff',
            name='from_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daysoff',
            name='month',
            field=models.CharField(blank=True, choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('', 'August'), ('', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='daysoff',
            name='month_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='daysoff',
            name='to_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daysoff',
            name='week_day',
            field=models.CharField(blank=True, choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=2, null=True),
        ),
    ]
